[package]
name = "simple_scene"
version = "0.1.0"
authors = ["Siebencorgie <siebencorgie@googlemail.com>"]

[dependencies]
jakar-engine = { path = "../../" }

vulkano = "0.6.1"
vulkano-shader-derive = "0.6.1"
vulkano-win = "0.6.1"

winit = "0.7.5"
cgmath = "0.15.0"
